### ISSUE TITLE
add-bl.py error

### ISSUE THREAD

**Issue by fantasticair** [chaoszhang/A-pro#8]
Hello,
I do not like the lack of terminal branches, you can add a dummy branch length, as in this [script.](URL) The input file is astral's output tree file, the command is `python2 add-bl.py out.add-bl.tree out.tre` or `python2 add-bl.py out.add-bl.tree out.tre outgroupname`, but I get this error `TypeError: Unrecognized or unsupported arguments: {'rooted': True}`, can you give me some advice to run it?

Best wishes

**Comment by smirarab** [comment]
Please let me know what version of dendropy you have. If you don't know, you can run:

~~~bash
python -c 'import dendropy; print(dendropy.__version__)'
~~~

**Comment by fantasticair** [comment]
hello，
I use your recommend command `python -c 'import dendropy; print(dendropy.__version__)'`, the result is `4.2.0`.

Best.

**Comment by smirarab** [comment]
I fixed the script. You didn't mention where you got the script, so to be sure, here is the path: https://github.com/smirarab/global/blob/master/src/mirphyl/utils/add-bl.py
If you got it from somewhere else, please let me know so that I can fix that location too. 

By the way, the new version works with python3 as well, so you don't need to write python2. Any python should work.

**Comment by fantasticair** [comment]
Thanks for your upgrade the script. I got the script from `https://github.com/chaoszhang/A-pro/issues/URL` but now couldn't find it.
